### ISSUE TITLE
Aborted after blocksize=0, why?

### ISSUE THREAD

**Issue by Miqdad325** [Chris78/sl2decode#3]
I used Lowrance hook sensor to collect some depth data in the sea. The data is logged into an sl2 file. When I tried to decode that file, I got the blooksize=0 error after only 33% of the file has been processed. Why would the file be corrupted? I simply attached the sensor to an autonomous boat that I control romotely. please help.

**Comment by Chris78** [comment]
Can you upload the sl2 file somewhere and provide a link to it?
Maybe I can have a look into it.
I don't know why files may be corrupt. 
But if you read a block of size 0 then you wouldn't know where to point the pointer to to continue reading the next block.
One option would be to move the pointer forward by 1 byte, then try to read from there and if no "valid" data can be read, move the pointer by one more byte, try to read from there and so on... until you find a position from where valid data can be read again.

**Comment by Miqdad325** [comment]
You can find the file here https://github.com/Miqdad325/sll2File

I should read 1 byte, then read another header (144 bytes)?

**Comment by Chris78** [comment]
Yes, in the case of h['blockSize']==0 you could start a loop in which you increase block_offset by 1 (for each loop) and try to read from there (just like in lines 74 to 77). Then examine the data in the hash h if it looks good (for example is the temperature in the expected range or are the lat/long in the expected range). If not increase block_offset by 1 again (continue the loop).
If the data is looking good however, break out of the loop and let the script continue from there.

**Comment by Miqdad325** [comment]
Can you please add this feature? I am not familiar with ruby. I would greatly appreciate it, it's quite important for my research. Thanks!

**Comment by Chris78** [comment]
[sl2decode.zip](https://github.com/Chris78/sl2decode/files/7266354/sl2decode.zip)

I added the loop that searches for the next readable block.
The check if the read data is "looking good" is based on your lat/long range (taken from the first output produced).

Looks like it can decode most of your file now. You'll see in logging output that there are a few more corrupt hiccups in your sl2 file. The resulting csv is about 3 times larger now, so I think it's more or less complete.

**Comment by Miqdad325** [comment]
Thank you!. It works now

**Comment by Chris78** [comment]
Glad I could help you.

What is your research about? (just curious...)

**Comment by Miqdad325** [comment]
My research is about marine monitoring using autonomous USVs. We take different measurements such as depth, water temperature etc.

**Comment by Chris78** [comment]
I see. I wish you success.
